%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/youssufsaleh/Dropbox (Neurological Conditions)/CHAPAS data (1)/questionnaire/Questionnaires_essentials.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/22 09:09:03

%% Import the data
[~, ~, raw] = xlsread('/Users/youssufsaleh/Dropbox (Neurological Conditions)/CHAPAS data (1)/questionnaire/Questionnaires_essentials.xlsx','Sheet1');
raw = raw(2:37,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[52,53,54]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
All_Qs = table;

%% Allocate imported array to column variable names
All_Qs.participantID = data(:,1);
All_Qs.BNSS_ANHEDONIA = data(:,2);
All_Qs.BNSS_ASOCIALITY = data(:,3);
All_Qs.BNSS_AVOLITION = data(:,4);
All_Qs.BNSS_BLUNTED = data(:,5);
All_Qs.BNSS_ALOGIA = data(:,6);
All_Qs.BNSS_TOTAL = data(:,7);
All_Qs.PANSS_POS_TOTAL = data(:,8);
All_Qs.PANSS_GRAND_TOTAL = data(:,9);
All_Qs.CALGARY_TOTAL = data(:,10);
All_Qs.BACS_VM_Z = data(:,11);
All_Qs.BACS_DS_Z = data(:,12);
All_Qs.BACS_TMT_Z = data(:,13);
All_Qs.BACS_VF_Z = data(:,14);
All_Qs.BACS_SC_Z = data(:,15);
All_Qs.BACS_ToL_Z = data(:,16);
All_Qs.BACS_TOTAL_Z = data(:,17);
All_Qs.ACE_ATTENTION = data(:,18);
All_Qs.ACE_MEMORY = data(:,19);
All_Qs.ACE_FLUENCY = data(:,20);
All_Qs.ACE_LANGUAGE = data(:,21);
All_Qs.ACE_VISUOSPATIAL = data(:,22);
All_Qs.ACE_TOTAL = data(:,23);
All_Qs.PSP_TOTAL = data(:,24);
All_Qs.SHAPS_TOTAL = data(:,25);
All_Qs.AMI1 = data(:,26);
All_Qs.AMI2 = data(:,27);
All_Qs.AMI3 = data(:,28);
All_Qs.AMI4 = data(:,29);
All_Qs.AMI5 = data(:,30);
All_Qs.AMI6 = data(:,31);
All_Qs.AMI7 = data(:,32);
All_Qs.AMI8 = data(:,33);
All_Qs.AMI9 = data(:,34);
All_Qs.AMI10 = data(:,35);
All_Qs.AMI11 = data(:,36);
All_Qs.AMI12 = data(:,37);
All_Qs.AMI13 = data(:,38);
All_Qs.AMI14 = data(:,39);
All_Qs.AMI15 = data(:,40);
All_Qs.AMI16 = data(:,41);
All_Qs.AMI17 = data(:,42);
All_Qs.AMI18 = data(:,43);
All_Qs.AMI_TOTAL = data(:,44);
%create AMI subscores and transform into correct format. 18 questions and 3
%sub domains and final scores are divided by the number of All_Qs (6 per domain
% and 18 all together: 
%Behavioural = 5+9+10+11+12+15./6
All_Qs.AMIB = (All_Qs.AMI5 + All_Qs.AMI9 + ...
All_Qs.AMI10 + All_Qs.AMI11 + All_Qs.AMI12 +...
All_Qs.AMI15)./6;
%emotional = 1+6+7+13+16+18./6
All_Qs.AMIE = (All_Qs.AMI1 + All_Qs.AMI6 + ...
All_Qs.AMI7 + All_Qs.AMI13 + All_Qs.AMI16 +...
All_Qs.AMI18)./6;
%social = 2+3+4+8+14+17
All_Qs.AMIS = (All_Qs.AMI2 + All_Qs.AMI3 + ...
All_Qs.AMI4 + All_Qs.AMI8 + All_Qs.AMI14 +...
All_Qs.AMI17)./6;
All_Qs.DoB = data(:,45);
All_Qs.Gender = data(:,46);
All_Qs.DoFEP = data(:,47);
All_Qs.DoTesting = data(:,48);
All_Qs.Dose = data(:,49);
All_Qs.Clz_level = data(:,50);
All_Qs.Nor_Clz = data(:,51);
All_Qs.OtherM1 = stringVectors(:,1);
All_Qs.OtherM2 = stringVectors(:,2);
All_Qs.Notes = stringVectors(:,3);
All_Qs.BMI = data(:,55);
All_Qs.Diabetes = data(:,56);
All_Qs.Glucose = data(:,57);
All_Qs.Age = data(:,58);


%% Clear temporary variables
clearvars data raw stringVectors R;

%% Clear temporary variables
clearvars data raw stringVectors R;

%% This next section plots the correlation matrix between All_Qs.
% It is worth defining some of these All_Qs as I am unfamiliar with
% quite a few off them: 

% 1. BACS: Brief assessment of cognition in Schizophrenia. 
% 2. PANS: Positive and negative syndrome scale.
% 3. BNSS: Brief negative symptoms scale. 
% 4. AMI: Apathy Motivation index. THis has three components 

% plot correlation matrix. 
[R,PValue,H] = corrplot(All_Qs(:,{'BNSS_ANHEDONIA', 'BNSS_ASOCIALITY',  ...
 'BNSS_AVOLITION','BNSS_BLUNTED','BNSS_ALOGIA',...
 'PANSS_POS_TOTAL','PANSS_GRAND_TOTAL' 'SHAPS_TOTAL'...
 'CALGARY_TOTAL','BACS_TOTAL_Z','ACE_TOTAL','AMI_TOTAL',...
 'AMIB','AMIE','AMIS','BMI','Clz_level','Dose','Age','Gender'})  ,                     ...
 'type','Pearson','testR','on','rows','pairwise');

  
  %% subplot relevant regressions. 
  
  % relationship between apathy and negative symptoms. 
  c=@cmu.colors;
  close all
  subplot (1,3,3)
    h = scatterRegress(All_Qs.BNSS_ASOCIALITY,All_Qs.BMI ...
     ,50,...
     'MarkerFaceColor',c('pastel blue'),...
     'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    ylabel('BMI')
    xlabel('BNSS total')
    title('BMI vs BNSS-total')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);
    
    
    
  hold on 
  subplot(1,3,2)
    h = scatterRegress(All_Qs.BNSS_ANHEDONIA,All_Qs.BMI ...
      ,50,...
      'MarkerFaceColor',c('pastel blue'),...
      'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    xlabel('Age')
    ylabel('BNSS anhedonia')
    title('BMI vs. BNSS_ anhedonia')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);hold on;
  
    hold on 
  subplot(1,3,1)
    h = scatterRegress(All_Qs.SHAPS_TOTAL,All_Qs.BMI ...
      ,50,...
      'MarkerFaceColor',c('pastel blue'),...
      'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    xlabel('SHAPS')
    ylabel('BMI')
    title('BMI vs SHAPS')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);hold on;
  
    %relationship between apathy and depression. 
    close all
  subplot (1,3,1)
    h = scatterRegress(All_Qs.AMI_TOTAL,All_Qs.CALGARY_TOTAL ...
     ,50,...
     'MarkerFaceColor',c('pastel blue'),...
     'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    ylabel('Calgary Depression Scale (CDS)')
    xlabel('AMI-(Total)')
    title('1. AMI-T vs CDS')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);
    
    
    
  hold on 
  subplot(1,3,2)
    h = scatterRegress(All_Qs.AMIB,All_Qs.CALGARY_TOTAL ...
      ,50,...
      'MarkerFaceColor',c('pastel blue'),...
      'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    xlabel('AMI-(Behavioural)')
    ylabel('Calgary Depression Scale (CDS)')
    title('2. AMI-B vs. CDS')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);hold on;
  
    hold on 
  subplot(1,3,3)
    h = scatterRegress(All_Qs.BNSS_TOTAL,All_Qs.CALGARY_TOTAL ...
      ,50,...
      'MarkerFaceColor',c('pastel blue'),...
      'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    xlabel('Brief Negative Symptoms Scale (BNSS)')
    ylabel('Calgary Depression Scale (CDS)')
    title('3. BNSS vs CDS')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);hold on;

    
    % relationship between cognition, apathy and negative scores. 
   
     close all
  subplot (1,3,1)
    h = scatterRegress(All_Qs.AMIB,All_Qs.BACS_ToL_T ...
     ,50,...
     'MarkerFaceColor',c('pastel blue'),...
     'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    ylabel('Brief Assessment of Cognition in Schizophrenia')
    xlabel('AMI-(Behaviour)')
    title('1. AMI-B vs BACS')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);
    
    
    
  hold on 
  subplot(1,3,2)
    h = scatterRegress(All_Qs.PANS_NEG_TOTAL,All_Qs.BACS_ToL_T ...
      ,50,...
      'MarkerFaceColor',c('pastel blue'),...
      'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    ylabel('Brief assessment of cognition in schizophrenia (BACS)')
    xlabel('Positive and negative symptoms in Schizophrenia - negative subscale')
    title('2. PANS-neg vs. BACS')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);hold on;
  
    hold on 
  subplot(1,3,3)
    h = scatterRegress(All_Qs.BNSS_TOTAL,All_Qs.BACS_ToL_T ...
      ,50,...
      'MarkerFaceColor',c('pastel blue'),...
      'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    ylabel('Brief Assessment of Cognition in Schizophrenia (BACS)')
    xlabel('Brief negative symptoms')
    title('3. BNSS vs BACS')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);hold on;
  
    
    
    
   
    % relationsip between apathy, negative symptoms, depression and
    % acceptance rates. 
  
    % proportion of offers accepted per subject. 
  accept_prop=accept./125;
  close all
  subplot (1,4,1)
    h = scatterRegress(All_Qs.AMIE,accept_prop ...
     ,50,...
     'MarkerFaceColor',c('pastel blue'),...
     'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    ylabel('Proportion offers accepted')
    xlabel('AMI-(Total)')
    title('1. AMI-T vs Accepted offers')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);
    
      subplot (1,4,2)
    h = scatterRegress(All_Qs.AMI_TOTAL,accept_prop ...
     ,50,...
     'MarkerFaceColor',c('pastel blue'),...
     'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    ylabel('Proportion offers accepted')
    xlabel('AMI-(Behaviour)')
    title('2. AMI-B vs Accepted offers')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);
  
  
   subplot (1,4,3)
    h = scatterRegress(All_Qs.BNSS_TOTAL,accept_prop ...
     ,50,...
     'MarkerFaceColor',c('pastel blue'),...
     'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    ylabel('Proportion offers accepted')
    xlabel('Brief negative symptom scale for schizophrenia (BNSS)')
    title('3. BNSS vs Accepted offers')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);
 
     subplot (1,4,4)
    h = scatterRegress(All_Qs.CALGARY_TOTAL,accept_prop ...
     ,50,...
     'MarkerFaceColor',c('pastel blue'),...
     'MarkerEdgeColor','none');
    AX = h;
    set(findall(gca,'Type','Line'),'LineWidth',1.5,'Color',c('brick red')...
      ,'LineStyle','--');
    ylabel('Proportion offers accepted')
    xlabel('Calgary Depression Scale (CDS)')
    title('4. CDS vs Accepted offers')
    set(gca,'fontSize',10,'fontWeight','normal','LineWidth',1);
 
 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
