%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/youssufsaleh/Dropbox (Neurological Conditions)/CHAPAS data (1)/questionnaire/Questionnaires.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/05 17:49:38

%% Import the data
[~, ~, raw] = xlsread('/Users/youssufsaleh/Dropbox (Neurological Conditions)/CHAPAS data (1)/questionnaire/Questionnaires.xlsx','Sheet1');
raw = raw(1:35,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[121,122]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
Questionnaires1 = table;

%% Allocate imported array to column variable names
Questionnaires1.participantD = data(:,1);
Questionnaires1.SHAPS1 = data(:,2);
Questionnaires1.SHAPS2 = data(:,3);
Questionnaires1.SHAPS3 = data(:,4);
Questionnaires1.SHAPS4 = data(:,5);
Questionnaires1.SHAPS5 = data(:,6);
Questionnaires1.SHAPS6 = data(:,7);
Questionnaires1.SHAPS7 = data(:,8);
Questionnaires1.SHAPS8 = data(:,9);
Questionnaires1.SHAPS9 = data(:,10);
Questionnaires1.SHAPS10 = data(:,11);
Questionnaires1.SHAPS11 = data(:,12);
Questionnaires1.SHAPS12 = data(:,13);
Questionnaires1.SHAPS13 = data(:,14);
Questionnaires1.SHAPS14 = data(:,15);
Questionnaires1.SHAPS_TOTAL = data(:,16);
Questionnaires1.AMI1 = data(:,17);
Questionnaires1.AMI2 = data(:,18);
Questionnaires1.AMI3 = data(:,19);
Questionnaires1.AMI4 = data(:,20);
Questionnaires1.AMI5 = data(:,21);
Questionnaires1.AMI6 = data(:,22);
Questionnaires1.AMI7 = data(:,23);
Questionnaires1.AMI8 = data(:,24);
Questionnaires1.AMI9 = data(:,25);
Questionnaires1.AMI10 = data(:,26);
Questionnaires1.AMI11 = data(:,27);
Questionnaires1.AMI12 = data(:,28);
Questionnaires1.AMI13 = data(:,29);
Questionnaires1.AMI14 = data(:,30);
Questionnaires1.AMI15 = data(:,31);
Questionnaires1.AMI16 = data(:,32);
Questionnaires1.AMI17 = data(:,33);
Questionnaires1.AMI18 = data(:,34);
Questionnaires1.AMI_TOTAL = data(:,35);
Questionnaires.AMIB = (Questionnaires.AMI5 + Questionnaires.AMI9 + ...
Questionnaires.AMI10 + Questionnaires.AMI11 + Questionnaires.AMI12 +...
Questionnaires.AMI15)./6;
%emotional = 1+6+7+13+16+18./6
Questionnaires.AMIE = (Questionnaires.AMI1 + Questionnaires.AMI6 + ...
Questionnaires.AMI7 + Questionnaires.AMI13 + Questionnaires.AMI16 +...
Questionnaires.AMI18)./6;
%social = 2+3+4+8+14+17
Questionnaires.AMIS = (Questionnaires.AMI2 + Questionnaires.AMI3 + ...
Questionnaires.AMI4 + Questionnaires.AMI8 + Questionnaires.AMI14 +...
Questionnaires.AMI17)./6;
%Total 
Questionnaires.AMI_Transform = Questionnaires.AMI_TOTAL./18;
Questionnaires1.BNSS1 = data(:,36);
Questionnaires1.BNSS2 = data(:,37);
Questionnaires1.BNSS3 = data(:,38);
Questionnaires1.BNSS_ANHEDONIA = data(:,39);
Questionnaires1.BNSS4 = data(:,40);
Questionnaires1.BNSS_DISTRESS = data(:,41);
Questionnaires1.BNSS5 = data(:,42);
Questionnaires1.BNSS6 = data(:,43);
Questionnaires1.BNSS_ASOCIALITY = data(:,44);
Questionnaires1.BNSS7 = data(:,45);
Questionnaires1.BNSS8 = data(:,46);
Questionnaires1.BNSS_AVOLITION = data(:,47);
Questionnaires1.BNSS9 = data(:,48);
Questionnaires1.BNSS10 = data(:,49);
Questionnaires1.BNSS11 = data(:,50);
Questionnaires1.BNSS_BLUNTED = data(:,51);
Questionnaires1.BNSS12 = data(:,52);
Questionnaires1.BNSS13 = data(:,53);
Questionnaires1.BNSS_ALOGIA = data(:,54);
Questionnaires1.BNSS_TOTAL = data(:,55);
Questionnaires1.CALGARY_DEPRESSION = data(:,56);
Questionnaires1.CALGARY_HOPELESS = data(:,57);
Questionnaires1.CALGARY_SELFDEPRECIATE = data(:,58);
Questionnaires1.CALGARY_GUILTY_IDEAS = data(:,59);
Questionnaires1.CALGARY_PATHOLOGICAL_GUILT = data(:,60);
Questionnaires1.CALGARY_MORNING_DEPRESS = data(:,61);
Questionnaires1.CALGARY_EARLY_WAKE = data(:,62);
Questionnaires1.CALGARY_SUICIDE = data(:,63);
Questionnaires1.CALGARY_OBSERVED_DEPRESS = data(:,64);
Questionnaires1.CALGARY_TOTAL = data(:,65);
Questionnaires1.PANSS_P1 = data(:,66);
Questionnaires1.PANSS_P2 = data(:,67);
Questionnaires1.PANSS_P3 = data(:,68);
Questionnaires1.PANSS_P4 = data(:,69);
Questionnaires1.PANSS_P5 = data(:,70);
Questionnaires1.PANSS_P6 = data(:,71);
Questionnaires1.PANSS_P7 = data(:,72);
Questionnaires1.PANSS_POS_TOTAL = data(:,73);
Questionnaires1.PANSS_N1 = data(:,74);
Questionnaires1.PANSS_N2 = data(:,75);
Questionnaires1.PANSS_N3 = data(:,76);
Questionnaires1.PANSS_N4 = data(:,77);
Questionnaires1.PANSS_N5 = data(:,78);
Questionnaires1.PANSS_N6 = data(:,79);
Questionnaires1.PANSS_N7 = data(:,80);
Questionnaires1.PANS_NEG_TOTAL = data(:,81);
Questionnaires1.PANSS_G1 = data(:,82);
Questionnaires1.PANSS_G2 = data(:,83);
Questionnaires1.PANSS_G3 = data(:,84);
Questionnaires1.PANSS_G4 = data(:,85);
Questionnaires1.PANSS_G5 = data(:,86);
Questionnaires1.PANSS_G6 = data(:,87);
Questionnaires1.PANSS_G7 = data(:,88);
Questionnaires1.PANSS_G8 = data(:,89);
Questionnaires1.PANSS_G9 = data(:,90);
Questionnaires1.PANSS_G10 = data(:,91);
Questionnaires1.PANSS_G11 = data(:,92);
Questionnaires1.PANSS_G12 = data(:,93);
Questionnaires1.PANSS_G13 = data(:,94);
Questionnaires1.PANSS_G14 = data(:,95);
Questionnaires1.PANSS_G15 = data(:,96);
Questionnaires1.PANSS_G16 = data(:,97);
Questionnaires1.PANSS_GEN_TOTAL = data(:,98);
Questionnaires1.BACS_VM_Z = data(:,99);
Questionnaires1.BACS_VM_T = data(:,100);
Questionnaires1.BACS_DS_Z = data(:,101);
Questionnaires1.BACS_DS_T = data(:,102);
Questionnaires1.BACS_TMT_Z = data(:,103);
Questionnaires1.BACS_TMT_T = data(:,104);
Questionnaires1.BACS_VF_Z = data(:,105);
Questionnaires1.BACS_VF_T = data(:,106);
Questionnaires1.BACS_SC_Z = data(:,107);
Questionnaires1.BACS_SC_T = data(:,108);
Questionnaires1.BACS_ToL_Z = data(:,109);
Questionnaires1.BACS_ToL_T = data(:,110);
Questionnaires1.BACS_TOTAL_Z = data(:,111);
Questionnaires1.BACS_TOTAL_T = data(:,112);
Questionnaires1.ACE_ATTENTION = data(:,113);
Questionnaires1.ACE_MEMORY = data(:,114);
Questionnaires1.ACE_FLUENCY = data(:,115);
Questionnaires1.ACE_LANGUAGE = data(:,116);
Questionnaires1.ACE_VISUOSPATIAL = data(:,117);
Questionnaires1.ACE_TOTAL = data(:,118);
Questionnaires1.PSP_TOTAL = data(:,119);
Questionnaires1.Age = data(:,120);
Questionnaires1.Gender = categorical(stringVectors(:,1));
Questionnaires1.notes = stringVectors(:,2);

%% Clear temporary variables
clearvars data raw stringVectors R;

%% This next section plots the correlation matrix between questionnaires.
% It is worth defining some of these questionnaires as I am unfamiliar with
% quite a few off them: 

% 1. BACS: Brief assessment of cognition in Schizophrenia. 
% 2. PANS: Positive and negative syndrome scale.
% 3. BNSS: Brief negative symptoms scale. 
% 4. AMI: Apathy Motivation index. THis has three components 

% plot correlation matrix. 
[R,PValue,H] = corrplot(Questionnaires(:,{'ACE_TOTAL', 'BACS_TOTAL_T',   ...
'AMI_TOTAL','AMIB','AMIE','AMIS','BNSS_ANHEDONIA','BNSS_AVOLITION', ...
    'CALGARY_TOTAL','PANS_NEG_TOTAL','BNSS_TOTAL'})  ,                  ...
    'type','Pearson','testR','on','rows','pairwise');


  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
